version: '3.8'
services:
 postgres:
   container_name: postgres_container
   image: postgres
   ports:
      - ${POSTGRES_PORT}:5432
   volumes:
      - ~apps/postgres:/var/lib/postgresql/data
   environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
   env_file:
      - .env
volumes:
  postgres: